### ISSUE TITLE
Applinking receber recibos via string

### ISSUE THREAD

**Issue by guilhermebruzzi** [stone-payments/Android-Uri-demo#5]
Recibo do cliente e do estabelecimento em 2 parâmetros: customerReceipt e merchantReceipt
Tanto para pagamento quanto para estorno

**Comment by jgabrielfreitas** [comment]
@guilhermebruzzi tem os modelos ai?

**Comment by guilhermebruzzi** [comment]
@jgabrielfreitas claro! :D
Vou mandar os recibos da nossa geladeira que a sitef gera com a Stone como adquirente mesmo:
Recibo do cliente:

                 STONE                 
          Mastercard Credito           
     ************8543  Via Cliente     
  VTEX INTERMEDIACAO DE COBRANCA LTDA  
          15/02/2017 20:09:16          
            Valor: R$ 2,48             
        DOC: 150017150217200916        
       Stone Id: 14670298138833        


                               (SiTef)

Recibo do estabelecimento:	

                 STONE                 
          Mastercard Credito           
 ************8543  Via Estabelecimento 
       Data: 15/02/2017 20:09:16       
            Valor: R$ 2,48             
        DOC: 150017150217200916        
       Stone Id: 14670298138833        


                               (SiTef)
