### ISSUE TITLE
Mudança de nome de parametros na ida e na volta do fluxo de pagamento

### ISSUE THREAD

**Issue by guilhermebruzzi** [stone-payments/Android-Uri-demo#7]
Parâmetros de ida do pagamento:
- acquirerId: string (e.g. "<stone_code>") // <- iremos incluir nas chamadas
- installments: int (e.g. 3 parcelas) // ok
- paymentType: string (e.g. "credit" or "debit") // ok
- amount: long (e.g. 1034) // ok
- transactionId: string (e.g.: "1093019039") // ok
- paymentId: string (e.g.: "1093019888") // <- Adicionar
- scheme:  string // <- mudar o nome

ex.: stone-payment://payment/?parametrosIda&scheme=instore // <- mudar o host de como faz esse link

Retorno:
ex.: instore://payment/?parametrosVolta // <- mudar o host de como faz esse link

- paymentId: string (e.g.: "1093019888") // <- salvar e retornar o mesmo
- acquirerTid: string (e.g. "<stone_itk>")
- acquirerAuthorizationCode: string (e.g. "<stone_atk>")
- customerReceipt: string (returned by the app) // <- incluido em outra issue
- merchantReceipt: string (returned by the app) // <- incluido em outra issue
- responsecode (0 = ok, !0 -> reason = <error_msg>) // <- mudar o nome
- reason: string // <- mudar o nome

**Comment by jgabrielfreitas** [comment]
Adicionar o tampo `taxes` do tipo **boolean** para transações com juros

**Comment by guilhermebruzzi** [comment]
Boa @jgabrielfreitas e o padrão desse taxes é ou receber o parâmetro com um valor como: "true" na URI do applinking ou nem receber (quase um checkbox)
