### ISSUE TITLE
Mudança de nome de parametros na ida e na volta do fluxo de estorno

### ISSUE THREAD

**Issue by guilhermebruzzi** [stone-payments/Android-Uri-demo#8]
Ida do estorno (payment-reversal):
ex.: Cappta://payment-reversal/?parametrosIda&scheme=instore // <- mudar o nome da action

- paymentId: string (e.g.: "1093019888")
- scheme:  string (e.g.: instore)

Retorno:
ex.: instore://payment-reversal/?parametrosVolta // <- retornar com o mesmo nome

- customerReceipt: string (returned by the app) // <- já pedido em outra issue
- merchantReceipt: string (returned by the app) // <- já pedido em outra issue
- responsecode (0 = ok, !0 -> reason = <error_msg>)
- reason: string

**Comment by tatimagdalena** [comment]
Adicionar nos parâmetros de ida o campo 

> acquirerId: string (e.g. "<stone_code>")
